### ISSUE TITLE
Latest firmware version? 1.0.2 my board's KIT-INFO.TXT says 1.04.013C

### ISSUE THREAD

**Issue by deepcoder** [MicrochipTech/AVR-IoT-WG-Sensor-Node#3]
Are these versions for different parts of component? Or?

Thx.

**Comment by luciodj** [comment]
Yes, the kit-info.txt file contains the version of the USB programmer/debugger chip firmware.
This is distinct from the version of the AVR firmware (which can be had from the command line  with the "version" command.
